FROM jupyter/scipy-notebook:latest

# Install Java
USER root
RUN apt-get update && apt-get install -y openjdk-17-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install PySpark
RUN pip install pyspark findspark

# Set JAVA_HOME environment variable
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-arm64/

# Set Spark environment variables
ENV SPARK_HOME=/opt/conda/lib/python3.11/site-packages/pyspark

# Switch back to jovyan user
USER $NB_UID

# Set Spark environment variables
ENV PATH=$JAVA_HOME/bin:$SPARK_HOME/bin:$PATH

# Install additional packages
RUN pip install s2sphere yapf black isort jupyter_contrib_nbextensions

# Disable password prompt for jupyter
RUN echo "c.NotebookApp.token = ''" >> /home/jovyan/.jupyter/jupyter_notebook_config.py